name: Check the source code
on:
  push:
    branches:
      - master
  pull-request:
    branches:
      - master
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: prettier --write .
      # - name: Lint
      #   run: npm run lint
